steps:
  # Step 1: Build Docker image using Dockerfile from the /muemo folder
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA', './muemo']

  # Step 2: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'muemo'
      - '--image'
      - 'gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

# Specify the service account for the build
serviceAccount: 'projects/muemo-454320/serviceAccounts/950251872768-compute@developer.gserviceaccount.com'
