# Use the official Python image from the Docker Hub
FROM python:3.10.0

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt and runtime.txt
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy your application code
COPY . .

# Specify the command to run your app
CMD ["python", "app.py"]